
/**
 * Represents a traditional remedy.
 */
export interface Remedy {
  /**
   * The name of the remedy.
   */
  name: string;
  /**
   * The description of the remedy.
   */
  description: string;
  /**
   * The symptom that the remedy addresses.
   */
  symptom: string;
  /**
   * The URL of the schematic image for the remedy.
   */
  imageUrl: string;
  /**
   * Optional flag indicating if the remedy was generated by AI.
   */
  isGenerated?: boolean;
}

/**
 * Represents a cached remedy entry.
 */
interface CachedRemedyEntry {
    remedies: Remedy[];
    timestamp: number; // Timestamp of when the data was cached
}

// Simple in-memory cache. Replace with a more robust solution (e.g., Redis, Memcached) for production.
const remedyCache = new Map<string, CachedRemedyEntry>();
const CACHE_EXPIRY_TIME = 60 * 60 * 1000; // 1 hour in milliseconds

// Implementation of `fetchRemediesFromSource` is located in a separate file so
// unit tests can easily spy on it without loading it upfront.
export { fetchRemediesFromSource } from './remedies-source';

/**
 * Retrieves validated traditional remedies based on symptom and language,
 * utilizing a server-side cache.
 *
 * @param symptom The symptom to filter remedies by.
 * @param language The language to filter remedies by.
 * @returns A promise that resolves to an array of Remedy objects.
 */
export async function getRemedies(symptom: string, language: string): Promise<Remedy[]> {
  const cacheKey = `${symptom || 'all'}-${language || 'default'}`;

  if (remedyCache.has(cacheKey)) {
    const cachedEntry = remedyCache.get(cacheKey)!;
    if (Date.now() - cachedEntry.timestamp < CACHE_EXPIRY_TIME) {
      console.log(`Cache hit for key: ${cacheKey}`);
      return cachedEntry.remedies;
    } else {
      remedyCache.delete(cacheKey);
      console.log(`Cache expired for key: ${cacheKey}`);
    }
  }

  console.log(`Cache miss for key: ${cacheKey}. Fetching from source...`);
  // Dynamically import to allow tests to spy on the function.
  const { fetchRemediesFromSource } = await import('./remedies-source');
  const freshRemedies = await fetchRemediesFromSource(symptom, language);

  // Store the fresh data in the cache
  // Cache even if freshRemedies is empty to avoid repeated source lookups for non-existent data
  // or for general queries that might not have specific results initially.
  const newCacheEntry: CachedRemedyEntry = {
      remedies: freshRemedies,
      timestamp: Date.now(),
  };
  remedyCache.set(cacheKey, newCacheEntry);
  console.log(`Stored data in cache for key: ${cacheKey} (Items: ${freshRemedies.length})`);

  return freshRemedies;
}

// Exported only for testing to reset the cache between tests
export function clearRemedyCache() {
  remedyCache.clear();
}


    