
/**
 * Represents a traditional remedy.
 */
export interface Remedy {
  /**
   * The name of the remedy.
   */
  name: string;
  /**
   * The description of the remedy.
   */
  description: string;
  /**
   * The symptom that the remedy addresses.
   */
  symptom: string;
  /**
   * The URL of the schematic image for the remedy.
   */
  imageUrl: string;
  /**
   * Optional flag indicating if the remedy was generated by AI.
   */
  isGenerated?: boolean;
}

/**
 * Represents a cached remedy entry.
 */
interface CachedRemedyEntry {
    remedies: Remedy[];
    timestamp: number; // Timestamp of when the data was cached
}

// Simple in-memory cache. Replace with a more robust solution (e.g., Redis, Memcached) for production.
const remedyCache = new Map<string, CachedRemedyEntry>();
const CACHE_EXPIRY_TIME = 60 * 60 * 1000; // 1 hour in milliseconds

/**
 * Fetches remedies directly from the source (mock data for now).
 * In a real application, this would fetch from Firestore or an API.
 *
 * @param symptom The symptom to filter remedies by.
 * @param language The language (currently unused in mock).
 * @returns A promise that resolves to an array of Remedy objects.
 */
async function fetchRemediesFromSource(symptom: string, language: string): Promise<Remedy[]> {
    console.log(`Fetching remedies from source for symptom: ${symptom}, language: ${language}`);
    // This expanded mock data should be replaced with actual database calls.
    const allRemedies: Remedy[] = [
      // Common Ailments
      { name: 'Gingembre ak Lem (Soj)', description: 'Mélange bu tang jër gingembre (ginger) ak lem bu saf pour calmer soj (toux). Defaral ko infusion.', symptom: 'toux', imageUrl: 'https://images.unsplash.com/photo-1565077174997-15cef3495342?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Lem ak Miel (Soj)', description: 'Ndoxum lem ak miel, baxna lool ci soj. Presse lem, yokk ci miel touti.', symptom: 'toux', imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Infusion Thym (Mettitu baat)', description: 'Infusion bu tang jër ak xob yu wow thym pour soulager mettitu baat (mal de gorge).', symptom: 'mal de gorge', imageUrl: 'https://images.unsplash.com/photo-1605031531091-3254111250d9?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Nana Menthe (Métit bop)', description: 'Laal ay xob u nana (menthe poivrée) wala def ko infusion bu sedd pour soulager métit bop (mal de tête).', symptom: 'mal de tête', imageUrl: 'https://images.unsplash.com/photo-1556262866-6f4c54c8052d?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Kinkeliba (Seuf)', description: 'Infusion kinkeliba bu tang, baxna pour wàññi fièvre (seuf) ak nettoyer yaram.', symptom: 'fièvre', imageUrl: 'https://images.pexels.com/photos/7775639/pexels-photo-7775639.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Argile Verte (Biir buy daw)', description: 'Diluer touti argile verte ci ndox mu bari, naan ko pour calmer biir buy daw (diarrhée). Attention, demander avis médical si ça persiste.', symptom: 'diarrhée', imageUrl: 'https://images.pexels.com/photos/7259989/pexels-photo-7259989.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Ail (Soj bu sedd)', description: 'Lek touti ail cru (garlic) wala boolé ko ci sa ñam pour renforcer système immunitaire contre le rhume (soj bu sedd).', symptom: 'rhume', imageUrl: 'https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Oignon ak Sucre (Sirop Soj)', description: 'Dagg oignon en rondelles, saupoudrer ak sucre, bayi ko mu reposer. Naan sirop bi formé pour calmer soj.', symptom: 'toux', imageUrl: 'https://images.pexels.com/photos/144206/pexels-photo-144206.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Eau Salée (Gargarisme Baat)', description: 'Faire gargarisme ak ndoxum xorom (eau salée) tiède plusieurs fois par jour pour soulager mettitu baat.', symptom: 'mal de gorge', imageUrl: 'https://images.unsplash.com/photo-1600352710195-761845456125?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Moringa (Fatigue/Conduite)', description: 'Def powder moringa ci sa ñam wala naan ko ak ndox pour yokk énergie (doole) ndax day bari vitamines.', symptom: 'fatigue', imageUrl: 'https://images.unsplash.com/photo-1630500680978-0690a7518e40?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Attaya ak Nana (Digestion)', description: 'Naan attaya après repas, surtout bi am nana, pour faciliter digestion ak éviter ballonnement.', symptom: 'digestion', imageUrl: 'https://images.pexels.com/photos/5946647/pexels-photo-5946647.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Ditax (Constipation)', description: 'Manger pulpe de ditax wala def ko jus pour aider transit intestinal en cas de constipation (biir bu tëye).', symptom: 'constipation', imageUrl: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Charbon Végétal (Ballonnement)', description: 'Naan charbon végétal activé ak ndox pour absorber gaz yi ci biir ak soulager ballonnement.', symptom: 'ballonnement', imageUrl: 'https://images.pexels.com/photos/1579708/pexels-photo-1579708.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Graines de Lin (Constipation)', description: 'Tremper graines de lin dans l\'eau et boire le gel formé pour lubrifier les intestins.', symptom: 'constipation', imageUrl: 'https://images.unsplash.com/photo-1507920166819-a916060596b6?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Verveine (Digestion difficile)', description: 'Infusion de verveine (verveine) après repas copieux pour aider la digestion.', symptom: 'digestion', imageUrl: 'https://images.pexels.com/photos/7615461/pexels-photo-7615461.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Ananas (Digestion)', description: 'Manger de l\'ananas frais pour ses enzymes (bromélaïne) qui aident à digérer les protéines.', symptom: 'digestion', imageUrl: 'https://images.unsplash.com/photo-1550258984-dc415967997f?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Fenouil (Gaz/Ballonnement)', description: 'Mâcher des graines de fenouil (fennel) ou boire une infusion pour réduire les gaz.', symptom: 'ballonnement', imageUrl: 'https://images.pexels.com/photos/4110101/pexels-photo-4110101.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Huile de Neem (Yaram)', description: 'Diwlin huile de neem (neem oil) si kaw problème derm (yaram) yu ndaw ndaw comme ay boutons wala gaañu gaañu.', symptom: 'peau', imageUrl: 'https://images.unsplash.com/photo-1570715004310-1d731a50f50e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile de Baobab (Yaram wow)', description: 'Appliquer huile de baobab (buy) sur peau sèche (yaram wow) pour hydrater et adoucir. Riche en vitamines.', symptom: 'peau', imageUrl: 'https://images.pexels.com/photos/8975688/pexels-photo-8975688.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Aloe Vera (Lakku yu ndaw)', description: 'Appliquer gel aloe vera frais sur brûlure légère (lakku yu ndaw) pour apaiser et cicatriser.', symptom: 'brûlure', imageUrl: 'https://images.unsplash.com/photo-1520085213989-3d9f8de17665?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Beurre de Karité (Yaram wow)', description: 'Utiliser beurre de karité (karité) brut pour hydrater profondément la peau très sèche ou gercée.', symptom: 'peau', imageUrl: 'https://images.pexels.com/photos/5797900/pexels-photo-5797900.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Miel (Cicatrisation)', description: 'Appliquer du miel pur sur une petite plaie propre pour ses propriétés antibactériennes et cicatrisantes.', symptom: 'plaie', imageUrl: 'https://images.unsplash.com/photo-1600352700265-3e7cf087614e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Plantain (Piqûres insectes)', description: 'Écraser des feuilles de plantain et appliquer sur les piqûres d\'insectes pour calmer les démangeaisons.', symptom: 'piqûre', imageUrl: 'https://images.pexels.com/photos/50605/plantain-plantago-lanceolata-good-king-henry-medical-plant-50605.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Calendula (Irritation Peau)', description: 'Utiliser une pommade ou une huile de calendula pour apaiser les irritations cutanées légères.', symptom: 'peau', imageUrl: 'https://images.unsplash.com/photo-1596039060980-a5ab5c8f0ea0?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile de Coco (Peau / Cheveux)', description: 'Huile de coco (ndekatou gnarr) comme hydratant pour la peau ou masque nourrissant pour les cheveux.', symptom: 'peau', imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Argile Blanche (Masque Visage)', description: 'Mélanger argile blanche avec de l\'eau pour un masque purifiant et adoucissant pour le visage.', symptom: 'peau', imageUrl: 'https://images.pexels.com/photos/7259991/pexels-photo-7259991.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Clou de Girofle (Mettitu beñ)', description: 'Mâcher un clou de girofle wala appliquer huile essentielle sur la dent douloureuse pour soulager temporairement mettitu beñ (mal de dents). Consultation dentiste nécessaire.', symptom: 'mal de dents', imageUrl: 'https://images.unsplash.com/photo-1599730043158-35a2726353a5?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Curcuma (Anti-inflammatoire)', description: 'Boolé touti curcuma (turmeric) ci sa ñam wala ci lait chaud pour ses propriétés anti-inflammatoires.', symptom: 'inflammation', imageUrl: 'https://images.unsplash.com/photo-1582215067260-eff071600a6f?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile d\'Arachide (Massage Douleurs)', description: 'Utiliser huile d\'arachide (gerte) tiède pour masser zones douloureuses (muscles, articulations).', symptom: 'douleur musculaire', imageUrl: 'https://images.pexels.com/photos/6787570/pexels-photo-6787570.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Arnica (Coups, Bleus)', description: 'Appliquer gel ou huile d\'arnica sur les contusions (bleus) ou douleurs musculaires légères.', symptom: 'douleur musculaire', imageUrl: 'https://images.unsplash.com/photo-1604085572504-1345dd101611?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Harpagophytum (Douleurs Articulaires)', description: 'Prendre des gélules ou une décoction d\'harpagophytum (griffe du diable) pour soulager les douleurs articulaires (en complément avis médical).', symptom: 'douleur articulaire', imageUrl: 'https://images.pexels.com/photos/7468993/pexels-photo-7468993.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Piment de Cayenne (Douleurs)', description: 'Crème ou cataplasme à base de piment de Cayenne (capsaïcine) pour soulager douleurs musculaires ou nerveuses (attention, ça chauffe!).', symptom: 'douleur musculaire', imageUrl: 'https://images.unsplash.com/photo-1526346379139-8f9090c08530?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Vinaigre de Cidre (Crampes)', description: 'Mélanger vinaigre de cidre avec de l\'eau et du miel, boire pour aider à prévenir les crampes musculaires.', symptom: 'crampes', imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Thé de Citronnelle (Sommeil)', description: 'Naan infusion citronnelle (lemongrass) bu tang avant tëdd pour aider relaxation ak nélaw bu neex.', symptom: 'sommeil', imageUrl: 'https://images.unsplash.com/photo-1596016799236-d02968310065?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Camomille (Relaxation)', description: 'Infusion camomille bu tang, bax na pour relaxation, stress touti, ak avant nélaw.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1559339352-11b000910999?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Infusion de Corossol (Sommeil)', description: 'Xob u corossol (feuilles de corossol) def ko infusion pour favoriser sommeil et relaxation.', symptom: 'sommeil', imageUrl: 'https://images.pexels.com/photos/5966361/pexels-photo-5966361.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Valériane (Sommeil)', description: 'Prendre une infusion ou des gélules de racine de valériane pour aider à l\'endormissement (demander conseil).', symptom: 'sommeil', imageUrl: 'https://images.unsplash.com/photo-1620705399385-797f5a033004?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Passiflore (Anxiété)', description: 'Infusion de passiflore (fleur de la passion) pour aider à calmer l\'anxiété légère et la nervosité.', symptom: 'anxiété', imageUrl: 'https://images.unsplash.com/photo-1598199625350-4980e0560563?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Lavande (Relaxation)', description: 'Quelques gouttes d\'huile essentielle de lavande sur l\'oreiller ou dans un bain chaud pour la détente.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1565015629979-999d8743a4a4?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Millepertuis (Humeur légère)', description: 'Infusion ou gélules de millepertuis pour soutenir l\'humeur (attention aux interactions médicamenteuses, avis médical).', symptom: 'humeur', imageUrl: 'https://images.pexels.com/photos/713297/pexels-photo-713297.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Bissap (Tension)', description: 'Jus de bissap bu sedd guiss, meun na aider réguler tension artérielle. Booléko ak touti sucre si besoin.', symptom: 'tension', imageUrl: 'https://images.unsplash.com/photo-1592079900725-f917c171025d?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Vinaigre de Cidre (Hoquet)', description: 'Naan touti vinaigre de cidre dilué dans de l\'eau pour essayer d\'arrêter le hoquet (sikim).', symptom: 'hoquet', imageUrl: 'https://images.unsplash.com/photo-1603575360127-3218519e5b3d?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Fenugrec (Stimuler Appétit)', description: 'Naan infusion graines de fenugrec (methi) pour stimuler appétit (ubb apetit).', symptom: 'appétit', imageUrl: 'https://images.unsplash.com/photo-1607008419750-384998737d9d?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Nebeday (Moringa) - Diabète', description: 'Ay études préliminaires montrent que nebeday (moringa) peut aider à réguler glycémie. Demander avis doktoor avant.', symptom: 'diabète', imageUrl: 'https://images.pexels.com/photos/10673753/pexels-photo-10673753.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Goyave (Feuilles) (Diarrhée)', description: 'Infusion de feuilles de goyave (goyave) pour aider à contrôler la diarrhée.', symptom: 'diarrhée', imageUrl: 'https://images.unsplash.com/photo-1620404728253-25e10264f304?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Soupe de Carottes (Diarrhée enfant)', description: 'Soupe de carottes bien cuite et mixée, remède traditionnel pour la diarrhée des enfants (réhydratation).', symptom: 'diarrhée', imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Eau de Riz (Diarrhée)', description: 'Boire l\'eau de cuisson du riz (ndoxum ceeb) pour réhydrater et calmer la diarrhée.', symptom: 'diarrhée', imageUrl: 'https://images.pexels.com/photos/209501/pexels-photo-209501.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Ortie (Anémie légère)', description: 'Infusion d\'ortie (ortie), riche en fer, pour soutenir en cas d\'anémie légère (en complément traitement médical).', symptom: 'anémie', imageUrl: 'https://images.unsplash.com/photo-1585031354226-a0a4f6796478?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Prêle (Ongles/Cheveux fragiles)', description: 'Infusion ou gélules de prêle des champs, riche en silice, pour renforcer ongles et cheveux.', symptom: 'cheveux', imageUrl: 'https://images.pexels.com/photos/7699684/pexels-photo-7699684.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Bouillon d\'Os (Santé générale)', description: 'Bouillon d\'os (soupe kandia style) mijoté longtemps, riche en nutriments pour la santé générale.', symptom: 'santé générale', imageUrl: 'https://images.unsplash.com/photo-1598103442304-7149a1297e4b?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile Essentielle Tea Tree (Antiseptique)', description: 'Quelques gouttes d\'HE de tea tree diluées dans une huile végétale pour désinfecter petites coupures ou boutons.', symptom: 'antiseptique', imageUrl: 'https://images.unsplash.com/photo-1600095022864-090360c5075e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Cannelle (Glycémie)', description: 'Ajouter de la cannelle (cinnamon) aux plats ou boissons pourrait aider à réguler la glycémie (support, pas traitement).', symptom: 'diabète', imageUrl: 'https://images.unsplash.com/photo-1558108449-15f3486179e7?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Propolis (Maux de gorge)', description: 'Mâcher de la propolis brute ou utiliser un spray pour ses propriétés antibactériennes sur le mal de gorge.', symptom: 'mal de gorge', imageUrl: 'https://images.pexels.com/photos/7615458/pexels-photo-7615458.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Gingko Biloba (Mémoire)', description: 'Extrait de Ginkgo Biloba pour potentiellement améliorer la circulation cérébrale et la mémoire (avis médical).', symptom: 'mémoire', imageUrl: 'https://images.unsplash.com/photo-1615679953957-370ire_nana934f1?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile d\'Onagre (Syndrome prémenstruel)', description: 'Capsules d\'huile d\'onagre pour aider à soulager certains symptômes du SPM.', symptom: 'spm', imageUrl: 'https://images.pexels.com/photos/8962875/pexels-photo-8962875.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Maca (Énergie/Libido)', description: 'Poudre de Maca ajoutée aux smoothies ou boissons pour un boost d\'énergie et potentiellement la libido.', symptom: 'fatigue', imageUrl: 'https://images.unsplash.com/photo-1600403293942-80587f55310e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Boldo (Foie)', description: 'Infusion de feuilles de boldo pour soutenir la fonction hépatique (foie), souvent après excès.', symptom: 'digestion', imageUrl: 'https://images.pexels.com/photos/11490231/pexels-photo-11490231.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Spiruline (Nutriments)', description: 'Ajouter de la spiruline en poudre aux jus ou smoothies pour un apport en protéines et vitamines.', symptom: 'santé générale', imageUrl: 'https://images.unsplash.com/photo-1631701025545-330660772342?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Bardane (Détox Peau)', description: 'Décoction de racine de bardane pour aider à purifier la peau de l\'intérieur (acné, eczéma).', symptom: 'peau', imageUrl: 'https://images.pexels.com/photos/723030/pexels-photo-723030.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Réglisse (Toux/Estomac)', description: 'Infusion de racine de réglisse pour apaiser la toux et certains maux d\'estomac (attention à la tension).', symptom: 'toux', imageUrl: 'https://images.unsplash.com/photo-1569098644584-8f6922091327?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Vinaigre des 4 voleurs (Prévention)', description: 'Macération de plantes dans du vinaigre, utilisée traditionnellement pour se protéger des épidémies (antiseptique).', symptom: 'prévention', imageUrl: 'https://images.pexels.com/photos/5946080/pexels-photo-5946080.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Guimauve (Toux sèche)', description: 'Infusion de racine de guimauve pour adoucir la gorge et calmer la toux sèche.', symptom: 'toux', imageUrl: 'https://images.unsplash.com/photo-1603513490316-538ab7f2535e?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Eucalyptus (Voies respiratoires)', description: 'Inhalation de vapeur d\'eucalyptus ou infusion pour dégager les voies respiratoires.', symptom: 'rhume', imageUrl: 'https://images.unsplash.com/photo-1591416047983-79520ce89496?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Artichaut (Digestion/Foie)', description: 'Infusion de feuilles d\'artichaut pour stimuler la bile et aider la digestion des graisses.', symptom: 'digestion', imageUrl: 'https://images.unsplash.com/photo-1518736399962-36a9905c81d7?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Chardon Marie (Protection Foie)', description: 'Gélules ou teinture de Chardon Marie pour soutenir et protéger le foie (avis médical).', symptom: 'foie', imageUrl: 'https://images.pexels.com/photos/713297/pexels-photo-713297.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Re-using an image as placeholder for specific one
      { name: 'Millefeuille (Coupures)', description: 'Appliquer des feuilles fraîches écrasées de millefeuille (achillée) sur une petite coupure pour aider à arrêter le saignement.', symptom: 'plaie', imageUrl: 'https://images.unsplash.com/photo-1598032884000-247655f4547c?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Jus de Citron chaud (Détox matin)', description: 'Boire un verre d\'eau tiède avec du jus de citron le matin à jeun pour stimuler la digestion.', symptom: 'digestion', imageUrl: 'https://images.unsplash.com/photo-1607346370618-4755277f53c0?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Sauge (Maux de gorge/Transpiration)', description: 'Gargarisme d\'infusion de sauge pour mal de gorge, ou infusion à boire pour réduire transpiration excessive.', symptom: 'mal de gorge', imageUrl: 'https://images.unsplash.com/photo-1598062047129-119249e31c19?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile de Ricin (Constipation occasionnelle)', description: 'Petite quantité d\'huile de ricin par voie orale comme laxatif puissant (usage ponctuel, avis médical).', symptom: 'constipation', imageUrl: 'https://images.pexels.com/photos/7615459/pexels-photo-7615459.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Bourrache (Peau sèche/Toux)', description: 'Huile de bourrache en capsules pour la peau sèche, ou infusion de fleurs pour la toux.', symptom: 'peau', imageUrl: 'https://images.unsplash.com/photo-1619019044274-29a7979b280f?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Noix de Kola (Fatigue/Stimulant)', description: 'Mâcher de la noix de kola (gourou) pour un effet stimulant et coupe-faim temporaire.', symptom: 'fatigue', imageUrl: 'https://images.pexels.com/photos/8059117/pexels-photo-8059117.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Pissenlit (Détox/Diurétique)', description: 'Infusion de feuilles ou racine de pissenlit pour un effet diurétique léger et détoxifiant.', symptom: 'détox', imageUrl: 'https://images.unsplash.com/photo-1559348060-7d2f29f6a3aa?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Romarin (Mémoire/Circulation)', description: 'Infusion de romarin pour stimuler la mémoire et la circulation sanguine.', symptom: 'mémoire', imageUrl: 'https://images.unsplash.com/photo-1594034980893-9157d9ea3964?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Huile de Nigelle (Immunité)', description: 'Prendre de l\'huile de nigelle (cumin noir) pour renforcer le système immunitaire.', symptom: 'immunité', imageUrl: 'https://images.pexels.com/photos/8878336/pexels-photo-8878336.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Fumeterre (Problèmes de peau)', description: 'Infusion de fumeterre pour aider en cas de problèmes de peau comme l\'eczéma ou le psoriasis (interne).', symptom: 'peau', imageUrl: 'https://images.pexels.com/photos/7699688/pexels-photo-7699688.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Baies de Goji (Antioxydant)', description: 'Manger des baies de Goji séchées pour leur richesse en antioxydants.', symptom: 'santé générale', imageUrl: 'https://images.unsplash.com/photo-1567609412802-aa5811fbf143?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Infusion Hibiscus (Refroidissant)', description: 'Boire une infusion d\'hibiscus (bissap) bien fraîche pour se rafraîchir.', symptom: 'chaleur', imageUrl: 'https://images.unsplash.com/photo-1626072097437-093017139021?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Lapacho (Immunité)', description: 'Décoction d\'écorce de Lapacho (Pau d\'Arco) pour soutenir le système immunitaire.', symptom: 'immunité', imageUrl: 'https://images.pexels.com/photos/7699685/pexels-photo-7699685.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Cataire (Herbe à chat) (Relaxant)', description: 'Infusion de cataire pour un effet relaxant léger (similaire à la camomille).', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1603928484169-e29006f89b91?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Ginseng (Énergie/Adaptogène)', description: 'Prendre du ginseng (racine) pour l\'énergie et aider le corps à s\'adapter au stress (avis médical).', symptom: 'fatigue', imageUrl: 'https://images.unsplash.com/photo-1599730043158-35a2726353a5?q=80&w=300&h=200&fit=crop', isGenerated: false }, // Placeholder if specific ginseng not found
      { name: 'Myrtille (Yeux/Circulation)', description: 'Manger des myrtilles ou prendre un extrait pour la santé des yeux et la circulation.', symptom: 'yeux', imageUrl: 'https://images.unsplash.com/photo-1471943319113-6a070952fee1?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Angélique (Digestion/Stress)', description: 'Infusion de racine d\'angélique pour stimuler la digestion et calmer le stress.', symptom: 'digestion', imageUrl: 'https://images.pexels.com/photos/8962863/pexels-photo-8962863.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Coriandre (Digestion/Détox métaux lourds)', description: 'Utiliser coriandre fraîche dans les plats pour aider la digestion et potentiellement chélater les métaux lourds.', symptom: 'digestion', imageUrl: 'https://images.unsplash.com/photo-1593098110964-b04130a88638?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Astragale (Immunité)', description: 'Décoction de racine d\'astragale pour renforcer l\'immunité, souvent utilisée en prévention.', symptom: 'immunité', imageUrl: 'https://images.pexels.com/photos/723030/pexels-photo-723030.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Placeholder
      { name: 'Rhodiola (Stress/Fatigue)', description: 'Extrait de Rhodiola comme plante adaptogène pour gérer le stress et la fatigue mentale.', symptom: 'stress', imageUrl: 'https://images.pexels.com/photos/7468993/pexels-photo-7468993.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Placeholder
      { name: 'Basilic Sacré (Tulsi) (Stress/Immunité)', description: 'Infusion de Tulsi pour ses propriétés adaptogènes, calmantes et de soutien immunitaire.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1604425061613-798001f88a98?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Cannabis CBD (Douleur/Anxiété - si légal)', description: 'Huile ou fleurs de CBD (si légal et approprié) pour douleur chronique ou anxiété.', symptom: 'douleur chronique', imageUrl: 'https://images.unsplash.com/photo-1597601897623-990e8d7f8f16?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Boswellia (Anti-inflammatoire articulations)', description: 'Extrait de résine de Boswellia pour l\'inflammation articulaire (arthrose).', symptom: 'douleur articulaire', imageUrl: 'https://images.pexels.com/photos/9705789/pexels-photo-9705789.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Griffonia (Humeur/Sommeil - 5-HTP)', description: 'Extrait de Griffonia (source de 5-HTP) pour soutenir l\'humeur et le sommeil (avis médical).', symptom: 'humeur', imageUrl: 'https://images.pexels.com/photos/5472643/pexels-photo-5472643.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false },
      { name: 'Eleuthérocoque (Ginseng Sibérien) (Énergie)', description: 'Racine d\'Eleuthérocoque comme adaptogène pour l\'énergie physique et mentale.', symptom: 'fatigue', imageUrl: 'https://images.pexels.com/photos/7615461/pexels-photo-7615461.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Placeholder
      { name: 'Schisandra (Adaptogène/Foie)', description: 'Baies de Schisandra comme adaptogène général et pour soutenir le foie.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1509350349546-92c929b100b1?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Reishi (Champignon Immunité)', description: 'Extrait de champignon Reishi pour le soutien immunitaire et comme adaptogène.', symptom: 'immunité', imageUrl: 'https://images.unsplash.com/photo-1599134842236-8a3a6a37271c?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Cordyceps (Champignon Énergie)', description: 'Extrait de champignon Cordyceps pour l\'énergie et l\'endurance physique.', symptom: 'fatigue', imageUrl: 'https://images.unsplash.com/photo-1587449718908-f9a3955a3e45?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Ashwagandha (Stress/Sommeil)', description: 'Racine d\'Ashwagandha comme adaptogène puissant pour réduire le stress et améliorer le sommeil.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1615042803679-8a83f6916647?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Gotu Kola (Centella Asiatica) (Mémoire/Peau)', description: 'Gotu Kola pour la circulation cérébrale, la mémoire et la cicatrisation de la peau.', symptom: 'mémoire', imageUrl: 'https://images.pexels.com/photos/7615461/pexels-photo-7615461.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Placeholder
      { name: 'Mélisse (Calmant/Digestif)', description: 'Infusion de mélisse pour calmer les nerfs, l\'anxiété légère et les troubles digestifs liés au stress.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1604059210391-dd21988e6372?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Avoine (Parties Aériennes) (Nervin)', description: 'Teinture ou infusion d\'avoine fleurie comme tonique doux pour le système nerveux.', symptom: 'stress', imageUrl: 'https://images.unsplash.com/photo-1516684732201-f508c2d63553?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Houblon (Sommeil/Relaxant)', description: 'Infusion de cônes de houblon (souvent avec valériane) pour favoriser le sommeil.', symptom: 'sommeil', imageUrl: 'https://images.unsplash.com/photo-1519892338194-651b2b41848b?q=80&w=300&h=200&fit=crop', isGenerated: false },
      { name: 'Scutellaire (Calmant Anxiété)', description: 'Infusion ou teinture de scutellaire pour calmer l\'agitation et l\'anxiété.', symptom: 'anxiété', imageUrl: 'https://images.pexels.com/photos/713297/pexels-photo-713297.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }, // Placeholder
      { name: 'Solidage (Verge d\'or) (Reins/Allergies)', description: 'Infusion de solidage pour soutenir les reins et potentiellement aider avec les allergies saisonnières.', symptom: 'allergies', imageUrl: 'https://images.pexels.com/photos/129559/pexels-photo-129559.jpeg?auto=compress&cs=tinysrgb&w=300&h=200&dpr=1', isGenerated: false }
    ];

    // Filter logic based on symptom (simple substring match for mock)
    let filteredRemedies = allRemedies;
    if (symptom && symptom.trim() !== "") { // Ensure symptom is not empty before filtering
      const lowerCaseSymptom = symptom.toLowerCase();
      filteredRemedies = allRemedies.filter(remedy =>
        remedy.symptom.toLowerCase().includes(lowerCaseSymptom) ||
        remedy.name.toLowerCase().includes(lowerCaseSymptom) ||
        remedy.description.toLowerCase().includes(lowerCaseSymptom)
      );
    } else {
      // If no symptom is provided, return a subset or all remedies
      // For now, returning all if no symptom, adjust as needed (e.g., popular remedies)
      // To return a default set (e.g., first 10) when no symptom is provided:
      // filteredRemedies = allRemedies.slice(0, 10);
    }

    // Language filtering would be more complex in a real scenario.
    // For this mock, we assume all remedies are in Franco-Wolof.
    // A real implementation might fetch based on language or have translations.

    return filteredRemedies;
}

/**
 * Retrieves validated traditional remedies based on symptom and language,
 * utilizing a server-side cache.
 *
 * @param symptom The symptom to filter remedies by.
 * @param language The language to filter remedies by.
 * @returns A promise that resolves to an array of Remedy objects.
 */
export async function getRemedies(symptom: string, language: string): Promise<Remedy[]> {
  const cacheKey = `${symptom || 'all'}-${language || 'default'}`;

  if (remedyCache.has(cacheKey)) {
    const cachedEntry = remedyCache.get(cacheKey)!;
    if (Date.now() - cachedEntry.timestamp < CACHE_EXPIRY_TIME) {
      console.log(`Cache hit for key: ${cacheKey}`);
      return cachedEntry.remedies;
    } else {
      remedyCache.delete(cacheKey);
      console.log(`Cache expired for key: ${cacheKey}`);
    }
  }

  console.log(`Cache miss for key: ${cacheKey}. Fetching from source...`);
  const freshRemedies = await fetchRemediesFromSource(symptom, language);

  // Store the fresh data in the cache
  // Cache even if freshRemedies is empty to avoid repeated source lookups for non-existent data
  // or for general queries that might not have specific results initially.
  const newCacheEntry: CachedRemedyEntry = {
      remedies: freshRemedies,
      timestamp: Date.now(),
  };
  remedyCache.set(cacheKey, newCacheEntry);
  console.log(`Stored data in cache for key: ${cacheKey} (Items: ${freshRemedies.length})`);

  return freshRemedies;
}

    