import {
  ArrowRight,
  Baby,
  Calendar as CalendarIcon,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HeartPulse,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  PanelLeft,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Syringe,
  Star,
  Trash,
  User,
  Venus,
  Video,
  Stethoscope,
  X,
  Workflow,
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  video: Video,
  stethoscope: Stethoscope,
  baby: Baby,
  heartPulse: HeartPulse,
  syringe: Syringe,
  calendar: CalendarIcon,
  star: Star,
  venus: Venus,
  panelLeft: PanelLeft, // Sidebar toggle icon
};

export {Icons};
